"""Seed curriculum, agent, and pedagogy graph data for CT-GraphMAS."""

from __future__ import annotations

from .micro_knowledge import micro_graph_payload


CONCEPT_ALIASES: dict[str, list[str]] = {
    "concept_problem_decomposition": ["问题分解", "拆分任务", "分步", "子任务", "需求", "输入", "输出", "边界"],
    "concept_abstraction": ["抽象建模", "变量", "模型", "状态", "数据表示", "对象", "特征"],
    "concept_algorithm_design": ["算法设计", "流程", "伪代码", "循环", "条件", "排序", "遍历", "规则"],
    "concept_debug_evaluation": ["调试", "报错", "错误", "测试", "验证", "print", "断点", "traceback"],
    "concept_variable": ["变量", "赋值", "命名", "name", "identifier"],
    "concept_io": ["输入", "输出", "input", "print", "交互"],
    "concept_condition": ["条件", "if", "elif", "else", "判断", "分支", "布尔"],
    "concept_loop": ["循环", "for", "while", "遍历", "重复", "迭代"],
    "concept_list": ["列表", "数组", "list", "下标", "索引", "append"],
    "concept_function": ["函数", "def", "参数", "返回值", "return", "封装"],
    "concept_string": ["字符串", "str", "切片", "拼接", "format", "f-string"],
    "concept_operator": ["运算符", "比较", "逻辑运算", "and", "or", "not", "取余"],
    "error_syntax": ["SyntaxError", "语法错误", "冒号", "缩进", "括号", "拼写"],
    "error_name": ["NameError", "未定义", "变量名", "拼错", "作用域"],
    "error_type": ["TypeError", "类型错误", "int", "str", "类型转换"],
    "error_index": ["IndexError", "越界", "索引", "下标", "长度"],
    "pedagogy_coder": ["C-O-D-E-R", "CODER", "情境激活", "多维编排", "协同开发", "循环调试", "反思重构"],
    "pedagogy_adapt": ["ADAPT", "伴学", "诊断", "支架", "迁移"],
}


SEED_NODES: list[dict[str, object]] = [
    {
        "id": "system_ct_graphmas",
        "label": "CT-GraphMAS",
        "kind": "system",
        "description": "知识图谱增强多智能体的计算思维导向编程辅导系统。",
    },
    {
        "id": "layer_l1",
        "label": "L1 感知与认知整合中枢",
        "kind": "layer",
        "description": "接收学生提问、代码、错误信息、学习画像和图谱相关知识，形成结构化诊断，但不直接输出最终答案。",
    },
    {
        "id": "layer_l2",
        "label": "L2 计算思维教学推理层",
        "kind": "layer",
        "description": "由问题分解、抽象建模、算法设计、调试评价智能体协同生成支架。",
    },
    {
        "id": "layer_l3",
        "label": "L3 交互呈现层",
        "kind": "layer",
        "description": "将教学推理转译为同伴型、启发导师型或严格教练型表达，并执行反代写门控。",
    },
    {
        "id": "agent_p1",
        "label": "P1 问题分解智能体",
        "kind": "agent",
        "description": "帮助学生把真实任务拆成输入、处理、输出和边界条件。",
    },
    {
        "id": "agent_p2",
        "label": "P2 抽象建模智能体",
        "kind": "agent",
        "description": "引导学生识别变量、状态、数据结构与可迁移模型。",
    },
    {
        "id": "agent_p3",
        "label": "P3 算法设计智能体",
        "kind": "agent",
        "description": "围绕条件、循环、列表、函数组织伪代码和步骤。",
    },
    {
        "id": "agent_p4",
        "label": "P4 调试评价智能体",
        "kind": "agent",
        "description": "根据错误信息、测试样例和运行路径进行定位、验证与反思。",
    },
    {
        "id": "agent_companion",
        "label": "同伴型表达",
        "kind": "agent",
        "description": "用共同探索的语气降低初学者焦虑。",
    },
    {
        "id": "agent_tutor",
        "label": "启发导师型表达",
        "kind": "agent",
        "description": "用追问、提示和小步骤帮助学生保留思考空间。",
    },
    {
        "id": "agent_coach",
        "label": "严格教练型表达",
        "kind": "agent",
        "description": "强调依据、测试、边界和复盘，不替学生直接完成完整程序。",
    },
    {
        "id": "concept_problem_decomposition",
        "label": "问题分解",
        "kind": "ct_skill",
        "description": "把复杂任务拆成若干可完成的小问题，明确输入、处理、输出。",
    },
    {
        "id": "concept_abstraction",
        "label": "抽象建模",
        "kind": "ct_skill",
        "description": "从具体情境中抽取变量、规则、状态和数据表示。",
    },
    {
        "id": "concept_algorithm_design",
        "label": "算法设计",
        "kind": "ct_skill",
        "description": "将解决方案组织为有序步骤、伪代码、流程或函数。",
    },
    {
        "id": "concept_debug_evaluation",
        "label": "调试评价",
        "kind": "ct_skill",
        "description": "通过错误定位、测试样例、边界检查和反思改进程序。",
    },
    {
        "id": "concept_variable",
        "label": "变量与赋值",
        "kind": "python_concept",
        "description": "变量用于保存数据，赋值语句建立名称与值之间的关系。",
    },
    {
        "id": "concept_io",
        "label": "输入与输出",
        "kind": "python_concept",
        "description": "input 获取文本输入，print 输出运行结果或调试信息。",
    },
    {
        "id": "concept_condition",
        "label": "条件分支",
        "kind": "python_concept",
        "description": "if/elif/else 根据布尔条件选择不同执行路径。",
    },
    {
        "id": "concept_loop",
        "label": "循环结构",
        "kind": "python_concept",
        "description": "for/while 用于重复执行任务，常与计数、遍历和条件退出相关。",
    },
    {
        "id": "concept_list",
        "label": "列表与索引",
        "kind": "python_concept",
        "description": "列表保存有序数据，索引从 0 开始，访问越界会触发错误。",
    },
    {
        "id": "concept_function",
        "label": "函数封装",
        "kind": "python_concept",
        "description": "函数把可复用步骤封装为带参数和返回值的程序单元。",
    },
    {
        "id": "concept_string",
        "label": "字符串处理",
        "kind": "python_concept",
        "description": "字符串可以拼接、切片、格式化，也经常需要与数值类型转换。",
    },
    {
        "id": "concept_operator",
        "label": "运算符与表达式",
        "kind": "python_concept",
        "description": "比较、算术和逻辑运算符共同构成条件和计算表达式。",
    },
    {
        "id": "error_syntax",
        "label": "SyntaxError 语法错误",
        "kind": "error_pattern",
        "description": "常见于缺少冒号、括号不配对、缩进不一致或关键字拼写错误。",
    },
    {
        "id": "error_name",
        "label": "NameError 名称错误",
        "kind": "error_pattern",
        "description": "常见于变量未定义、命名不一致或作用域理解不足。",
    },
    {
        "id": "error_type",
        "label": "TypeError 类型错误",
        "kind": "error_pattern",
        "description": "常见于字符串和数字混用、函数参数类型不匹配等情境。",
    },
    {
        "id": "error_index",
        "label": "IndexError 索引越界",
        "kind": "error_pattern",
        "description": "常见于列表下标超出范围，通常需要检查长度和循环边界。",
    },
    {
        "id": "strategy_2hop",
        "label": "动态图谱路由",
        "kind": "strategy",
        "description": "优先围绕当前路由节点、先修节点和典型错误组织相关知识，不注入完整图谱以避免认知负荷。",
    },
    {
        "id": "strategy_lowdoc",
        "label": "少量相关知识",
        "kind": "strategy",
        "description": "只取少量高相关知识作为支架依据，保留反馈清晰度和响应效率。",
    },
    {
        "id": "gate_anti_ghostwrite",
        "label": "反代写门控",
        "kind": "guardrail",
        "description": "拦截全盘代写、事实误导和认知错位，优先给提示、伪代码和局部修复。",
    },
    {
        "id": "pedagogy_coder",
        "label": "C-O-D-E-R 教学流程",
        "kind": "workflow",
        "description": "情境激活、组织编排、协同开发、循环调试、反思重构的课堂流程。",
    },
    {
        "id": "pedagogy_adapt",
        "label": "ADAPT 伴学模式",
        "kind": "workflow",
        "description": "围绕诊断、支架、行动、练习和迁移的伴学流程。",
    },
    {
        "id": "theory_quasi_subject",
        "label": "类主体性多智能体",
        "kind": "theory",
        "description": "把智能体从工具定位转向可被教师编排、能参与课堂认知任务分工的类主体学习伙伴。",
    },
    {
        "id": "theory_adapt_companion",
        "label": "ADAPT 伴学理论",
        "kind": "theory",
        "description": "强调诊断、支架、行动、练习、迁移的连续伴学，让学生在被支持的同时保持主动建构。",
    },
    {
        "id": "theory_coder_classroom",
        "label": "C-O-D-E-R 课堂范式",
        "kind": "theory",
        "description": "把多智能体编程学习组织为情境激活、组织编排、协同开发、循环调试、反思重构。",
    },
    {
        "id": "agent_requirement",
        "label": "需求分析智能体",
        "kind": "agent",
        "description": "从真实情境中澄清用户、输入、处理规则、输出和约束。",
    },
    {
        "id": "agent_architecture",
        "label": "逻辑架构智能体",
        "kind": "agent",
        "description": "把需求转化为流程图、伪代码、模块边界和数据结构。",
    },
    {
        "id": "agent_pair_programming",
        "label": "配对编程智能体",
        "kind": "agent",
        "description": "以同伴方式给局部提示、追问和最小示例，不直接替学生完成整段程序。",
    },
    {
        "id": "agent_code_review",
        "label": "代码检查智能体",
        "kind": "agent",
        "description": "依据运行结果、报错信息和测试样例帮助学生定位问题。",
    },
    {
        "id": "agent_reflection",
        "label": "思维复盘智能体",
        "kind": "agent",
        "description": "把一次编程任务沉淀为可迁移的计算思维经验。",
    },
    {
        "id": "profile_novice",
        "label": "破冰期新手",
        "kind": "student_profile",
        "description": "需要问题分解、基础语法和低焦虑调试支持。",
    },
    {
        "id": "profile_intermediate",
        "label": "建构期中等生",
        "kind": "student_profile",
        "description": "需要算法流程、逻辑关系和错误选择性修复支架。",
    },
    {
        "id": "profile_advanced",
        "label": "自动化期进阶生",
        "kind": "student_profile",
        "description": "需要抽象建模、高阶调试、方案优化和迁移反思。",
    },
]


SEED_EDGES: list[dict[str, object]] = [
    {"source": "system_ct_graphmas", "target": "layer_l1", "relation": "HAS_LAYER", "weight": 1.0},
    {"source": "system_ct_graphmas", "target": "layer_l2", "relation": "HAS_LAYER", "weight": 1.0},
    {"source": "system_ct_graphmas", "target": "layer_l3", "relation": "HAS_LAYER", "weight": 1.0},
    {"source": "layer_l2", "target": "agent_p1", "relation": "HAS_AGENT", "weight": 1.0},
    {"source": "layer_l2", "target": "agent_p2", "relation": "HAS_AGENT", "weight": 1.0},
    {"source": "layer_l2", "target": "agent_p3", "relation": "HAS_AGENT", "weight": 1.0},
    {"source": "layer_l2", "target": "agent_p4", "relation": "HAS_AGENT", "weight": 1.0},
    {"source": "layer_l3", "target": "agent_companion", "relation": "HAS_STYLE", "weight": 0.9},
    {"source": "layer_l3", "target": "agent_tutor", "relation": "HAS_STYLE", "weight": 1.0},
    {"source": "layer_l3", "target": "agent_coach", "relation": "HAS_STYLE", "weight": 0.85},
    {"source": "agent_p1", "target": "concept_problem_decomposition", "relation": "SCAFFOLDS", "weight": 1.0},
    {"source": "agent_p2", "target": "concept_abstraction", "relation": "SCAFFOLDS", "weight": 1.0},
    {"source": "agent_p3", "target": "concept_algorithm_design", "relation": "SCAFFOLDS", "weight": 1.0},
    {"source": "agent_p4", "target": "concept_debug_evaluation", "relation": "SCAFFOLDS", "weight": 1.0},
    {"source": "concept_variable", "target": "concept_io", "relation": "PREREQUISITE_OF", "weight": 0.8},
    {"source": "concept_operator", "target": "concept_condition", "relation": "PREREQUISITE_OF", "weight": 0.9},
    {"source": "concept_condition", "target": "concept_loop", "relation": "PREREQUISITE_OF", "weight": 0.8},
    {"source": "concept_variable", "target": "concept_loop", "relation": "PREREQUISITE_OF", "weight": 0.7},
    {"source": "concept_loop", "target": "concept_list", "relation": "PREREQUISITE_OF", "weight": 0.8},
    {"source": "concept_variable", "target": "concept_function", "relation": "PREREQUISITE_OF", "weight": 0.7},
    {"source": "concept_string", "target": "error_type", "relation": "CAN_CAUSE", "weight": 0.7},
    {"source": "concept_variable", "target": "error_name", "relation": "CAN_CAUSE", "weight": 0.8},
    {"source": "concept_condition", "target": "error_syntax", "relation": "CAN_CAUSE", "weight": 0.7},
    {"source": "concept_list", "target": "error_index", "relation": "CAN_CAUSE", "weight": 0.8},
    {"source": "strategy_2hop", "target": "strategy_lowdoc", "relation": "PAIRS_WITH", "weight": 1.0},
    {"source": "strategy_2hop", "target": "concept_debug_evaluation", "relation": "SUPPORTS", "weight": 0.8},
    {"source": "gate_anti_ghostwrite", "target": "agent_tutor", "relation": "CONSTRAINS", "weight": 1.0},
    {"source": "gate_anti_ghostwrite", "target": "agent_coach", "relation": "CONSTRAINS", "weight": 1.0},
    {"source": "pedagogy_coder", "target": "concept_problem_decomposition", "relation": "ORGANIZES", "weight": 0.8},
    {"source": "pedagogy_coder", "target": "concept_algorithm_design", "relation": "ORGANIZES", "weight": 0.8},
    {"source": "pedagogy_coder", "target": "concept_debug_evaluation", "relation": "ORGANIZES", "weight": 0.8},
    {"source": "pedagogy_adapt", "target": "concept_abstraction", "relation": "ORGANIZES", "weight": 0.7},
    {"source": "theory_quasi_subject", "target": "agent_requirement", "relation": "DEFINES_ROLE", "weight": 0.9},
    {"source": "theory_quasi_subject", "target": "agent_architecture", "relation": "DEFINES_ROLE", "weight": 0.9},
    {"source": "theory_quasi_subject", "target": "agent_pair_programming", "relation": "DEFINES_ROLE", "weight": 0.9},
    {"source": "theory_quasi_subject", "target": "agent_code_review", "relation": "DEFINES_ROLE", "weight": 0.9},
    {"source": "theory_quasi_subject", "target": "agent_reflection", "relation": "DEFINES_ROLE", "weight": 0.9},
    {"source": "theory_coder_classroom", "target": "pedagogy_coder", "relation": "GROUNDS", "weight": 1.0},
    {"source": "theory_coder_classroom", "target": "agent_requirement", "relation": "ORCHESTRATES", "weight": 0.8},
    {"source": "theory_coder_classroom", "target": "agent_code_review", "relation": "ORCHESTRATES", "weight": 0.8},
    {"source": "theory_coder_classroom", "target": "agent_reflection", "relation": "ORCHESTRATES", "weight": 0.8},
    {"source": "theory_adapt_companion", "target": "pedagogy_adapt", "relation": "GROUNDS", "weight": 1.0},
    {"source": "theory_adapt_companion", "target": "concept_problem_decomposition", "relation": "SCAFFOLDS", "weight": 0.7},
    {"source": "theory_adapt_companion", "target": "concept_debug_evaluation", "relation": "SCAFFOLDS", "weight": 0.7},
    {"source": "profile_novice", "target": "agent_p1", "relation": "PREFERS", "weight": 1.0},
    {"source": "profile_novice", "target": "agent_p4", "relation": "PREFERS", "weight": 0.8},
    {"source": "profile_intermediate", "target": "agent_p3", "relation": "PREFERS", "weight": 1.0},
    {"source": "profile_intermediate", "target": "agent_p4", "relation": "PREFERS", "weight": 0.8},
    {"source": "profile_advanced", "target": "agent_p2", "relation": "PREFERS", "weight": 1.0},
    {"source": "profile_advanced", "target": "agent_p3", "relation": "PREFERS", "weight": 0.9},
]


MICRO_NODES, MICRO_EDGES = micro_graph_payload()
SEED_NODES.extend(MICRO_NODES)
SEED_EDGES.extend(MICRO_EDGES)
